# Generated by Django 5.0.4 on 2024-04-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0004_booking_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
    ]
